"""Detect ComfyUI node classes and requirements in a package directory."""

from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path

INIT_TEMPLATE = '''# Auto-generated by GenVR ComfyUI installer
{imports}

NODE_CLASS_MAPPINGS = {{
{mapping_entries}
}}

__all__ = ["NODE_CLASS_MAPPINGS"]
'''


def find_requirements_files(package_dir: Path, repo_root: Path | None = None) -> list[Path]:
    candidates = [package_dir / "requirements.txt"]
    if repo_root and repo_root != package_dir:
        candidates.append(repo_root / "requirements.txt")
    return [p for p in candidates if p.is_file()]


def discover_node_classes(package_dir: Path) -> dict[str, str]:
    """Return {node_name: module_path} for classes that look like ComfyUI nodes."""
    nodes: dict[str, str] = {}

    for py_file in package_dir.glob("*.py"):
        if py_file.name.startswith("_"):
            continue
        try:
            tree = ast.parse(py_file.read_text(encoding="utf-8"))
        except (SyntaxError, OSError):
            continue

        for node in tree.body:
            if not isinstance(node, ast.ClassDef):
                continue
            has_input = False
            has_comfy = False
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if item.name == "INPUT_TYPES":
                        has_input = True
                    if item.name in ("execute",) or item.name == getattr(item, "name", ""):
                        pass
                if isinstance(item, ast.Assign):
                    for target in item.targets:
                        if isinstance(target, ast.Name):
                            if target.id == "INPUT_TYPES":
                                has_input = True
                            if target.id in ("FUNCTION", "RETURN_TYPES", "CATEGORY"):
                                has_comfy = True
            if has_input and has_comfy:
                nodes[node.name] = py_file.stem

    return nodes


def ensure_init_py(package_dir: Path) -> tuple[Path | None, list[str]]:
    """
    Ensure __init__.py exports NODE_CLASS_MAPPINGS.
    Returns (init path, log messages).
    """
    init_path = package_dir / "__init__.py"
    logs: list[str] = []

    if init_path.exists():
        text = init_path.read_text(encoding="utf-8")
        if "NODE_CLASS_MAPPINGS" in text:
            logs.append(f"Found existing {init_path}")
            return init_path, logs

    nodes = discover_node_classes(package_dir)
    if not nodes:
        logs.append("No ComfyUI node classes detected; __init__.py not created")
        return init_path if init_path.exists() else None, logs

    imports = []
    entries = []
    for class_name, module_name in nodes.items():
        imports.append(f"from .{module_name} import {class_name}")
        entries.append(f'    "{class_name}": {class_name},')

    content = INIT_TEMPLATE.format(
        imports="\n".join(imports),
        mapping_entries="\n".join(entries),
    )
    init_path.write_text(content, encoding="utf-8")
    logs.append(f"Generated {init_path} with NODE_CLASS_MAPPINGS for: {', '.join(nodes)}")
    return init_path, logs


def install_requirements(req_files: list[Path]) -> list[dict]:
    """pip install -r for each requirements file. Returns per-file results."""
    results: list[dict] = []
    for req in req_files:
        proc = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-r", str(req)],
            capture_output=True,
            text=True,
        )
        results.append({
            "requirements_file": str(req),
            "success": proc.returncode == 0,
            "stdout": proc.stdout[-4000:] if proc.stdout else "",
            "stderr": proc.stderr[-4000:] if proc.stderr else "",
        })
    return results


def read_existing_mappings(package_dir: Path) -> list[str]:
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        return []

    try:
        tree = ast.parse(init_path.read_text(encoding="utf-8"))
    except (SyntaxError, OSError):
        return []

    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == "NODE_CLASS_MAPPINGS":
                if isinstance(node.value, ast.Dict):
                    names: list[str] = []
                    for key in node.value.keys:
                        if isinstance(key, ast.Constant) and isinstance(key.value, str):
                            names.append(key.value)
                    return names
    return []
